header:
  schema-version: 2.0.0
  last-updated: '2025-07-26'
  last-reviewed: '2025-07-26'
  url: https://github.com/openfga/flask-demo
  project-si-source: https://raw.githubusercontent.com/openfga/.github/main/SECURITY-INSIGHTS.yml
  comment: A demo application that uses FGA for access control written in Flask.

repository:
  url: https://github.com/openfga/flask-demo
  status: active
  bug-fixes-only: false
  accepts-change-request: true
  accepts-automated-change-request: true
  no-third-party-packages: false
  core-team:
  - name: Evan Sims
    affiliation: Okta
    email: evan.sims@okta.com
    social: https://github.com/evansims
    primary: true

  license:
    url: https://raw.githubusercontent.com/openfga/flask-demo/main/LICENSE
    expression: Apache-2.0

  documentation:
    contributing-guide: https://github.com/openfga/.github/blob/main/CONTRIBUTING.md
    dependency-management-policy: https://github.com/openfga/openfga/blob/main/docs/dependencies-policy.md
    governance: https://github.com/openfga/.github/blob/main/GOVERNANCE.md
    review-policy: https://github.com/openfga/.github/blob/main/CONTRIBUTING.md
    security-policy: https://github.com/openfga/flask-demo/SECURITY.md

  security:
    assessments:
      self:
        evidence: https://github.com/cncf/tag-security/blob/main/community/assessments/projects/openfga/joint-assessment.md
        date: '2024-12-19'
        comment: OpenFGA has completed a CNCF security joint assessment with CNCF TAG-Security

    tools:
      - name: Dependabot
        type: SCA
        version: latest
        rulesets:
          - built-in
        integration:
          adhoc: false
          ci: true
          release: true
        comment: Dependabot is enabled for this repository to automatically update dependencies.
      - name: Snyk
        type: SCA
        version: latest
        rulesets:
          - built-in
        integration:
          adhoc: false
          ci: true
          release: true
        comment: Snyk is enabled for this repository to scan for vulnerabilities.
